// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AuthProvider } from "@/context/auth-context";
// import ClientProvider from "@/components/client-provider";
// import { Toaster } from "sonner";
// import { ThemeProvider } from "next-themes";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans?.variable} ${geistMono?.variable} antialiased h-screen`}
//       >
//         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
//           <ClientProvider>
//             <AuthProvider>{children}</AuthProvider>
//             <Toaster position="top-right" closeButton />
//           </ClientProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
import ClientProvider from "@/components/client-provider";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "MedTrax - Medical Store Management System",
    template: "%s | MedTrax",
  },
  description: "Complete medical store management solution for inventory tracking, sales management, prescription handling, and billing. Streamline your pharmacy operations with MedTrax.",
  keywords: [
    "medical store management",
    "pharmacy software",
    "medicine inventory",
    "billing software",
    "prescription management",
    "medical store POS",
    "pharmacy management system",
    "stock management",
    "MedTrax",
  ],
  authors: [
    {
      name: "MedTrax Team",
      url: "https://pharma-vaults.vercel.app/",
    },
  ],
  creator: "MedTrax",
  publisher: "MedTrax",
  applicationName: "MedTrax",
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "../assets/MedTraxLogo.png" },
      { url: "../assets/MedTraxLogo.png", sizes: "16x16", type: "image/png" },
      { url: "../assets/MedTraxLogo.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [
      { url: "../assets/MedTraxLogo.png", sizes: "180x180", type: "image/png" },
    ],
  },
   
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  category: "Healthcare",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content="#0a0a0a" media="(prefers-color-scheme: dark)" />
      </head>
      <body
        className={`${geistSans?.variable} ${geistMono?.variable} antialiased h-screen`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ClientProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
            <Toaster 
              position="top-right" 
              closeButton 
              richColors
              expand={false}
              duration={3000}
            />
          </ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}